name: macOS-arm-build

on:
  push:
    branches: [master, 2.10.1]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  release:
    name: Build (macOS arm64 / Tcl 8.6)
    runs-on: macos-14

    steps:
      - name: check out git repository
        uses: actions/checkout@v4

      - name: build
        run: |
          brew install tcl-tk@8
          TCLTK_PREFIX="$(brew --prefix tcl-tk@8)"
          export PATH="$TCLTK_PREFIX/bin:$PATH"
          export LDFLAGS="-L$TCLTK_PREFIX/lib"
          export CPPFLAGS="-I$TCLTK_PREFIX/include"
          export PKG_CONFIG_PATH="$TCLTK_PREFIX/lib/pkgconfig"
          tclsh tcl-conf-arm
          make install arch=arm64

      - name: upload
        uses: actions/upload-artifact@v4.3.5
        with:
          name: macos-arm64
          path: cmake/runtime/lib/tkdnd2.10.1

  release-tcl9:
    name: Build (macOS arm64 / Tcl 9)
    runs-on: macos-14

    steps:
      - name: check out git repository
        uses: actions/checkout@v4

      - name: build
        run: |
          brew reinstall tcl-tk
          export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"
          export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"
          export PKG_CONFIG_PATH="/usr/local/opt/tcl-tk/lib/pkgconfig"
          tclsh tcl-conf-arm
          make install arch=arm64

      - name: upload
        uses: actions/upload-artifact@v4.3.5
        with:
          name: macos-arm64-tcl9
          path: cmake/runtime/lib/tkdnd2.10.1
